#+hugo_base_dir: ../
#+hugo_section: posts
#+hugo_auto_set_lastmod: t
#+macro: kbd @@html:<kbd>$1</kbd>@@

#+title: capture-001
#+date: 2023-06-02 Jun 16:42
#+math: true
#+hugo_tags: computation
#+hugo_categories: blog
#+hugo_custom_front_matter: :license ""


* Prelude
** Jargon
*** TODO Predicates
*** TODO Quantifiers
*** Alphabet
- An alphabet is simply some finite non-empty set $A$ of objets called symbols.
**** Words/Strings
- An n-tuple of symbols of $A$ is called a word or a string on $A$.
***** Properties of Words/Strings
Let $u,v \in A^*$,
- Concatenation: If $u=\text{bab}$ and $v=\text{abc}$ then $u \cdot v = \text{bababc}$.
*** Languages
- The set of all words on the alphabet $A$ is written as $A^*$ and any subset of $A^*$ is called a language on $A$.
*** Residues
- Consider a language $L = \{x \ | \ w.x \in L\}$ i.e string "$w$" is in the
  language iff it is followed by $x$ i.e $x$ leads to acceptance of $w$ so $x$
  here is called the *residue* which is also written as $L_/_w$ .
** Set Theory
- A set is a collection into a whole of some well recognized objects i.e the set's elements.
- As collections \equiv whole \equiv set implies that the definition is circular.
- So, the definition of set is based on a collective faith or some kind of intuition among humans.
*** Properties of sets
**** Equality
- Two sets are equal iff they have the exact same elements.
- This is also called the principle of extensionality which implies that a finite set can be defined by means of their elements.
- Another way to describe a set is by using the shared property of its elements ex. $\{x \ | \ \text{some property of x}\}$.
**** Relations
***** Subset
- We write $R \subseteq S$ and say that $R$ is a subset of $S$ which means that every element of $R$ is in $S$.
- Thus, $R = S$ iff $R \subseteq S$ and $S \subseteq R$.
- For any set $\phi \subseteq R$ and $R \subseteq R$.
****** Proper Subset
- When $R \subseteq S$ but $R \neq S$ then we say $R$ is a proper subset of $S$ and write it as $R \subset S$.
**** Powerset
- If $A$ is a set then the set $\mathbb{P}$ such that $\mathbb{P} = \{B \ | \ B \subseteq A\}$ is called the powerset of
  $A$ i.e the set of all subsets of $A$.
*** Operations on sets
**** Union
- $R \cup S$ is the collection of all objects which are members of either $R$ or $S$ or both.
**** Intersection
- $R \cap S$ is the collection of all objects which belong to both $R$ and $S$.
**** Difference
- $R-S$ is the collection of all objects which belong to $R$ but not $S$.
- Thus, $R-S = R - (R \cap S)$.
**** De-Morgan's Identities
- $\bar{R \cup S} = \bar{R} \cap \bar{S}$
- $\bar{R \cap S} = \bar{R} \cup \bar{S}$
*** Diagonalization
*** Russels Paradox
- The best definition in my opinion is from Stanford Encyclopedia of Philosophy,
  - "Russell’s paradox is the most famous of the logical or set-theoretical paradoxes. Also known as the Russell-Zermelo
    paradox, the paradox arises within naive set theory by considering the set of all sets that are not members of
    themselves. Such a set appears to be a member of itself if and only if it is not a member of itself. Hence the paradox. "
- To put it more formally, as I said that we can define a set by means of some shared property of its elements. Let the
  property be, $\phi(x)$ which is $x \in x$ then, a set $R = \{x \ | \ \neg\phi(x)\}$ is the set whose members are exactly those
  objects that are not members of themselves. The paradox is whether $R \in R$ or $R \notin R$.
- In Russel's own words,
  "The comprehensive class we are considering, which is to embrace everything, must embrace itself as one of its
  members. In other words, if there is such a thing as “everything,” then, “everything” is something, and is a member of the
  class “everything.” But normally a class is not a member of itself. Mankind, for example, is not a man. Form now the
  assemblage of all classes which are not members of themselves. This is a class: is it a member of itself or not? If it
  is, it is one of those classes that are not members of themselves, i.e., it is not a member of itself. If it is not,
  it is not one of those classes that are not members of themselves, i.e. it is a member of itself. Thus of the two
  hypotheses – that it is, and that it is not, a member of itself – each implies its contradictory. This is a
  contradiction."
**** Fix
We can fix this paradox by using Zermelo's separation principle which solves the paradox by taking any consistent set
$S$ and a $\phi(x)$ with free $x$, then there will be a set $\{x \in S \ | \ \phi(x)\}$. Now even if $\phi(x)$ is $x \notin x$ the
corresponding set will not be contradictory since it consists only of those members found within S that are not members of themselves. Hence the set fails to include itself.
**** TODO Implications
** Relations
*** Binary Relation
- A binary relation $R \subseteq A \times B$ is construed as a *process* of taking elements from $A$ and yields elements in $B$.
*** Properties of Relations
Let $R \subseteq A \times A$ i.e a binary relation from $A$ to $A$,
- Symmetric: $xRy \implies yRx$
- Transitive: $(xRy \ \& \ yRz) \implies xRz$
- Reflexive: $xRx \ \forall x \in A$
** Mappings
- A mapping is defined as a triplet $(A,R,B)$ where $R \subseteq A \times B$ we write $R: \ A \implies B$ as a mapping where
  $A$ is the domain and $B$ is the range.
*** Operations on Mappings
- Inverse: If $R: \ A \implies B$ then,  $R^{-1}: \ B \implies A$ is its inverse is defined as $xRy$ iff $yR^{-1}x$.
- Composition: If $R:\ A \implies B$ and $Q:\ B \implies C$ then $(R;Q): \ A \implies C$ is defined as $x(R;Q)z$ iff
  $xRy$ and $yRz$ for some $y \in B$.
*** Properties of Mappings
Let $R:\ A \implies B$ then,
- Univalent (Single Valued): $\forall x \in A$ there is *at-most one* $y\in B$ such that $xRy$.
- Injective (Single Sourced): $\forall y \in B$ there is *at-most one* $x \in A$ such that $xRy$.
- Total: $\forall x \in A$ there is *at-least one* $y \in B$ such that $xRy$.
- Surjective: $\forall y \in B$ there is *at-least one* $x \in A$ such that $xRy$.
If all three properties are valid for some relation then it is called an equivalence relation.
** Functions
- A function is a set $f$ all of whose members are ordered pairs and that has property, $(a,b) \in f \ \text{and} \ (a,c)
  \in f \ \text{implies} \ b = c$.
- Intuitively it's better to think of the pairs as the row of a table. For function $f$ one writes $f(a)=b$ to mean that
  $(a,b) \in f$ and the definition ensures that for each $a$ there can only be one $b$.
- The set of all $a$'s such that $(a,b) \in f$ is called the domain of $f$ and set of all $f(a)$ is called its range.
- $\phi$ is also a function considered on some set $S$ but it's just nowhere defined.
*** Partial Function
- A partial function on set $S$ is a function whose domain is a subset of $S$ that means its defined for some elements
  of $S$ but not for all elements.
- If $R: \ A \implies B$ is single valued we say that it is a partial function from $A$ to $B$ and write it as $R: \ A
  \rightharpoonup B$.
*** Total Function
- If a partial function on $S$ has the domain $S$ then its called a total function i.e its defined for all elements of $S$.
- If $R: \ A \implies B$ is single valued and total we say that it is a total function from $A$ to $B$ and write it as $R: \ A
  \rightarrow B$.
*** Injective Functions
- We say that $A \preccurlyeq B$ iff there exists an injection $E: \ A \rightarrow B$ where $A$ is size bounded by $B$ and the injection
  preserves size and $E$ is the size embedding of $A$ in $B$.
- Thus, instead of counting all elements of set to determine equivalence of sets we can say that $A \equiv B$ when $A \preccurlyeq B$
  and $B \preccurlyeq A$.
*** Bijections
- If a function $f: \ A \rightarrow B$ is both injective and surjective then it's called a bijection and write it as $A \cong B$.
- $f$ draws a one to one correspondence between elements of $A$ and $B$.
- Bijective functions are closed under inverse and composition.
** Induction
- It is a technique for proving statements of form $(\forall n)P(n)$ where $P$ is a predicate on $\mathbb{N}$. The process is
  as follows,
  + First we prove for auxiliary statement i.e $P(0)$. This is called the base step.
  + And then for $(\forall n)(\text{if} \ P(n) \ \text{then} \ P(n+1))$. For this we fix some arbitrary value for $n$ and call
    it $k$ then we *assume* $P(k)$ and prove $P(k+1)$. Here $P(k)$ is called the induction hypothesis and the step is
    called the induction step or generative step.
- Once the above statements are proved the original statement $(\forall n)P(n)$ is also proved as,
  - If $P(0)$ then $P(1)$,
  - If $P(1)$ then $P(2)$,
  - If $P(2)$ then $P(3)$ $\cdots$
- This might seem paradoxical as we are assuming $P(k)$ to be true which is what one is supposed to be proving but as
  $k$ is just some arbitrary $n$ and we are not assuming our original statement which we set out to prove i.e $(\forall
  n)P(n)$ it is not infact paradoxical.
** Mathematical Machines
- They are basically data handlers. It deals with discrete (individually separated) and finite data.
- The data is most of the times textual data.
- The computation terminates only after the end of input is reached.
*** Finite Automata
- A finite automata $M$ in the alphabet $A = \{s_1, s_2, \cdots, s_n\}$ with states $Q = \{q_1, q_2, \cdots, q_m\}$ is given by a
  function $\delta$ that maps each pair $(q_1, s_1)$ where $1 \le i \le m$, $1 \le j \le n$ into a state $q_k$ together with a set $F
  \subseteq Q$. One of the states usually $q_1$ is singled out and called the initial state. The states in $F$ are
  called final or accepting states and $\delta$ is called the transition function.
- The automata in above definition is also called a *DFA*.
**** Important Theorems
**** Clipping Property
"*If* $M$ is a $k$ state automaton over $\Sigma^*$ and $w\in\Sigma^*$ is accepted by $M$ and
$u$ is a substring of $w$ of length $\ge k$ *then* there exists a substring $y$ of
$u$ such that removing $y$ yields a $w^'$ which is still in $\Sigma^*$ and is
accepted by $M$"
- Property of all regular languages.
**** NFA
- It is same as *DFA* except that the $\delta$ is the set of states instead of a member of $Q$.
- An NDFA over alphabet $A$ and set of states $Q$ which is specified by giving a transition function $\delta$ which maos each
  pair $(q_i, s_j)$ into a possibly empty subset of $Q$ and a fixed subset $F \subseteq Q$,
  - $\delta^*(q_i, 0) = \{q_i\}$
  - $\delta^*(q_i, us_j) = \cup_{q \in \delta^*(q_u, u)} \delta(q, s_j)$
- Here, $\delta^*$ accumulates all states that the NFA can enter when it reaches the right end of $u$ beginning from the left
  end of $u$ in state $q_1$ and $u$ is accepted iff $\delta^*(q_1, u) \cap F \neq \phi$.
** Basic Languages
- Basic languages over $\Sigma$ are constructed with set operations of union, intersection, difference, kleene star, kleene plus from
  finite languages over $\Sigma$.
- That is to say,
  + Finite languages are basic.
  + If $L$ and $M$ are basic then so are $L \cup M$, $L \cap M$, $L - M$, $L^*$, $L^+$, $L.M$.
** Regular Languages
- A language is called regular if there is a finite automata that accepts it.
- Similar to basic languages except that for generation we only use union and as language operation we only use
  concatenation, kleene star.
*** Regular Expressions
- Regex is just a notation for regular languages.
*** Closure Properties
- If $L$ and $\bar{L}$ are regular languages then so is $L \cup \bar{L}$.
- If $L_1$ and $L_2$ are regular languages then so is $L_1 \cap L_2$.
- If $L \subseteq A^*$ is a regular language then so is $\bar{L}$ i.e $A^* - L$.
- $\phi$ and $\epsilon$ are regular languages.
*** Kleene's Theorem
A language is regular iff it can be obtained from a finite languages by applying the three operations $\cup, \cap, \star$ a finite
number of times.
** Symbolic Computing
- In symbolic computing there are no states.
- The rewrite rules act as the operational engine analogous to transition functions.
- Rewrite systems use auxiliary symbols dubbed non terminals to indicate computation's type of action and location.
- A rewrite system that generates a language is called a grammar.
- A grammar consists of,
  + $\Sigma$ the alphabet.
  + $N$ the set of non terminals.
  + $S$ the initial non terminal.
  + $R$ the set of rewrite rules.
*** CFG
- It is a grammar where every source in a rewrite rule is a non terminal.
- Languages produced by such a grammar are called context-free languages.
**** Closure Properties of CFL
Here both $L$ and $L'$are CFLs.
- $L\cup L'$ is a CFL as $S \rightarrow S_1 \ | \ S_2$
- $L\cdot L'$ is a CFL as $S \rightarrow S_1 \cdot S_2$
- $L^*$ is a CFL as $S \rightarrow S_1\cdot S$
**** Other Properties
- All regular languages are context-free but not all context free languages regular.
- Compliment of CFG may not be a CFG.
- $\text{CFL} \cap \text{RL} = \text{CFL}$
- $\text{CFL} - \text{RL} = \text{CFL}$
- $\text{RL} - \text{CFL} \neq \text{CFL}$
- $\text{CFL} - \text{CFL} \neq \text{CFL}$
**** Dual Clipping Theorem for CFLs
- Let $G$ be a CFG over $\Sigma$ with $m$ non terminals and all productions of degree $\le d$.
- If $w \in L(G)$ has length $\ge k$ where $k = d^m$ then,
  + $w$ has a sub-string $p$ of length $\le k$ with disjoint sub strings $y_0 \ \& \ y_1$ both non empty such that
    removing them from $w$ yields a $w'$ such that $w^{'} \in L(G)$.
*** Context Freedom Lemma
- As a descendant of one non terminal is different from descendent of another,
  $G = (\Sigma, N, S, R) \ \& \ \Gamma = \Sigma \cup N$ then if $u_0, u_1 \in \Gamma^*$ and $u_0\cdot u_1 \rightarrow^* y$ then $v = v_0 \cdot v_1$ such that $u_0
  \rightarrow^* v_0$ and $u_1 \rightarrow^* v_1$.
*** PDA
** More General Machines
*** 2DFA
*** LBA
* Parts of the story
** Models of Computations
- Turing machines
- lambda calculus
- cellular automata,
- pointer machines,
- bouncing billiards balls,
- Conway’s Game of life
*** Why are all these models equivalent?
- All models of computation are considered to be equivalent because they are all able to simulate each other with a polynomial time overhead. This means that any computation that can be performed by one model of computation can also be performed by another model of computation, albeit with a possibly longer running time.
The notion of equivalence among models of computation is based on the Church-Turing thesis, which states that all effective computations can be performed by a simple theoretical machine known as a Turing machine. This thesis implies that all models of computation that can simulate a Turing machine are equivalent in terms of their computational power.
There are many different models of computation, including the Turing machine, the Lambda calculus, and the Random access machine (RAM). These models are all considered to be equivalent because they can all simulate each other with a polynomial time overhead. This means that any computation that can be performed by one model of computation can also be performed by another model of computation, albeit possibly with a longer running time.
** Church-Turing Thesis
- The notion of "computability" is completely captured by Turing machines.
- Here "thesis" means a declaration of faith as no rigorous proof is possible due to circular reasoning. So, this thesis can never be definitively confirmed.
*** Evidence
- As information is based on discrete and unambiguous representation and can be therefore be given by discrete and recognized symbols laid out in space.
- Such layouts can be reduced to a 1-D layout as a discrete space can be specified by addresses.
- So, computation is indeed a discrete process as any computing device has discrete states and a finite state of transition rule.
- The device navigates through data and access it, modifies it.
** Scope of computing
*** Jargon
**** Decision Problems
- A decision problem is a request for an algorithm.
**** Instances
- Finite discrete objects which can be represented textually.
**** Solution
- An algorithm for deciding each instance whether it satisfies the property. If it satisfies then the problem is decidable else undecidable.
**** Semantics
- A program is a piece of text, its meaning is called semantics.
**** Semi-decidable or T-recognizable
- A problem is semi-decidable iff it is recognized (as a language) by a Turing acceptor.
***** Certificates
- Many decision problems are of for "There is for instance $X$ an object $c$ such that ..." here $c$ is a certificate for $x \in \mathcal{P}$.
- A certification for problem $P$ is a binary relation $\vdash_{P}$ between instances of $X$ of $P$ and string $c$ such that for every instance $X$: $X \in P$ iff $c \vdash X$ for some $c$.
- The relation $\vdash_{P}$ is a certificate for $P$ when $c \vdash_{P} X$ certifies that $X \in P$.
- Checking that a certificate $c$ for $X$ is a good one i.e $c \vdash X$ must be computationally easier than deciding $X$ without extra help.
- Ex. verification of some valid answer for an semi-decidable problem is easier than finding one. It is easier to check whether some $c$ divides $n$ than answering whether $n$ is composite.
***** Decidable Certification
- A certification $\vdash$ is of a problem $P$ is decidable if it is decidable as a set i.e there is an algorithm for deciding whether given $c$ and $X$ is $c \vdash X$.
***** TODO Semi-Decidable Certification
**** Computably Enumerated
- A problem $L \subseteq \Sigma^*$ is CE if there is a function $f: \mathbb{N} \rightarrow \Sigma^*$ with image $L$ i.e $L$ is the set of all output values that $f$ may produce.
**** Orderly Enumerated
- A language $L \subseteq \Sigma^*$ is OE if there is a computable injection $f: \mathbb{N} \rightarrow \Sigma^*$ with $|f(n)| \le |f(n+1)|$ whose image is $L$.
**** Computable Function
- A function $\rho:\ \Sigma^* \rightarrow \Sigma^*$ is computable if there is a TM $F$ such that $F$ on input $w$ halts with $\rho(w)$ on its tape for all $w \in \Sigma^*$.
**** Reductions
- How do we compare two decision problems? To answer this question we first see how we compare two sets.
  - $A \preccurlyeq B$ if there is an injection $f: \ A \rightarrow B$ . So, we compare using $f$ as a way to construe $A$ as a part of $B$ as $f$ is a special function that preserves size.
  - If there is a way to transform an algorithm solving $P$ into an algorithm solving $Q$ then, $P \preccurlyeq Q$.
***** What is it exactly?
- A reduction of a decision problem $P$ to problem $Q$ is a function,
  - $\rho : \ \text{Instances of P} \rightarrow \text{Instances of Q}$
    - s.t for every instance $X$ of $P$, $X \in P$ iff $\rho(X) \in Q$. Then we can write $\rho \ : P \preccurlyeq Q$
      | A: decidable   | B: $\perp$         |
      | A: undecidable | B: undecidable |
      | B: undecidable | A: $\perp$         |
      | B: decidable   | A: decidable   |
**** Trivial Property
- A property is trivial for a language $L$ if it is true of every $w \in L$ or
  true for none.
**** Denotational/stable Properties
- The denotation of a syntactic phrase is its dictionary meaning.
- The connotation of a syntactic phrase is its meaning in context.
- The denotation of a computing device is the thing it computes.
  - the denotation of an acceptor is a language.
  - the denotation of a transducer is a function.
- The connotation of a computing device is how it behaves.
  - internal making, resource consumed etc.
***** A property of an acceptor is Denotational/stable if it refers to the language recognized and nothing else.
- This implies that acceptor recognizing the same language have all the same Denotational/stable properties. Similarly, all transducers computing the same function share the same Denotational/stable properties.
- These properties are also called semantic or extensional properties.
**** Examples of denotational/stable properties of TM
- $L(M)$ is finite or infinite.
- $L(M)$ has at least two elements.
- $L(M)$ is regular.
*** Important Theorems
**** $L$ is SD iff it has a decidable certification
***** Explanation
- Suppose acceptor $M$ recognizes $L$ and let $c \vdash w$ iff $c$ is a trace of $M$ that accepts $w$.
- Then, $\vdash$ is a certification of $L$ by definition of $L(M) = L$.
- Moreover, $\vdash$ is decidable by an algorithm that checks the trace $c$.
**** An infinite language is decidable iff it is orderly enumerated.
***** Explanation
- Suppose $L$ is OE s.t $f(0) = \text{first w accepted by M}$ and $f(n+1) = \text{first w size-lex after f(n) accepted by M}$ where $M$ is a decider.
- Then, as $f$ is non-size decreasing injection by definition and infinite which implies $f$ is total and is computable by a decider $M$ we can say that $L$ is decidable language.
**** A non-empty problem is SD iff it is finite or computably enumerated.
***** Explanation
- If the language is finite then it is recognized by a TM?
- Suppose $L$ is an infinite recognized language, then it has a certificate $\vdash$.
- Since $\vdash$ is infinite decidable set it is orderly enumerated ($(c_1,w_1), (c_2, w_2) \cdots$) as it is decidable.
- So, $w_1, w_2 \cdot$ is a computable enumeration of $L$.
- Suppose $L$ is enumerated by a computable function $f: \mathbb{N} \rightarrow \Sigma^*$ then,  $L = L(M)$ where $M$ is an acceptor that on input $w$ calculates $f(0), f(1)\cdots$ and accepts $w$ if it is ever obtained as an output.
***** Corollary: $L$ is SD iff it has a decidable certificate.
**** If $A$ and $\bar{A}$ are T-recognizable (SD) the $A$ is decidable.
***** Intuition
- A decidable algorithm answers $\text{yes/no}$ correctly whereas a semi-decidable algorithm answers $\text{yes}$ correctly. So, decidability of $L$ is like having two semi-decidable algorithms one for $L$ and other for $\bar{L}$.
***** Proof
- Let TM $M_1$ and $M_2$ recognize $A$ and $\bar{A}$ respectively.
- Construct a TM $T$ which decides $A$.
- $T =$ on input $w$
  1. Run $M_1$ and $M_2$ on $w$ in parallel until any one accepts.
  2. If $M_1$ accepts then accept and if $M_2$ accepts then reject.
***** Corollary: $\bar{A_{TM}}$ is not T-recognizable / not SD.
As $A_{TM}$ is T-recognizable but undecidable.
**** $A$ is T-recognizable (SD) iff $A = L(E)$ for some T-enumerator E.
***** Proof
- Convert TM $M$ to equivalent enumerator $E$.
  $E =$ Simulate $M$ on each $w_i$ in $\Sigma^* = \{\epsilon, 0, 1, 00, 01 ...\}$.
  If M accepts $w_i$ then print $w_i$ and continue.
  If $M$ on $w_i$ loops then simulate $M$ on $w_1, w_2...w_i$ for $i = 1, 2, ...n$ and print those $w_i$ if accepted.
**** $A_{DFA}$ is decidable.
***** Proof
- Let $A_{DFA} = \{<B,w>\}$ s.t $B$ is a DFA and accepts $w$.
- $D_{A_{DFA}} =$ "On input s,
  1. Check that $s$ is of the correct form.
  2. Simulate the computation of $B$ on $w$.
  3. If $B$ ends in an accept state then accept, if not then reject.
- Similarly, $A_{NFA}$ is also decidable as we can have our first step to convert $B$ to equivalent DFA.
**** $E_{DFA}$ is decidable.
***** Proof
- Let $E_{DFA} = \{<B>\}$ s.t $B$ is a DFA and $L(B) = \phi$ and let TM $D_{E_{DFA}}$ be the decider s.t,
- $D_{E_{DFA}} =$ On input $<B>$,
  1. Marks the start state.
  2. Repeats until no new state is marked.
     1. Mark every state with incoming arrow from previous marked state.
  3. Accept if no accept state has been marked and reject if any accept state has been marked.
**** $A_{CFG}$ is decidable.
***** Proof
- Let $A_{CFG} = \{<G,w>\}$ s.t $G$ is a CFG and $w \in L(G)$ and let $D_{A_{CFG}}$ be its Turing decider.
- $D_{A_{CFG}} =$ on input $<G,w>$,
  1. Convert $G$ to CNF.
  2. Try all possible derivations of length $2|w|-1$.
  3. Accept if any generate $w$ else reject.
**** $E_{CFG}$ is decidable.
***** Proof
- Let $E_{CFG} = \{<B>\}$ s.t $B$ is a CFG and $L(B) = \phi$ and let TM $D_{E_{CFG}}$ be the decider s.t,
- $D_{E_{CFG}} =$ On input $<G>$,
  1. Marks all occurrences of terminals in $G$.
  2. Repeats until no new non-terminal is marked.
     1. Mark all occurrences of $A$ when $A \rightarrow B_1B_2..B_k$ is a rule where all $B_i$'s are already marked.
  3. Accept if start nonterminal is marked and reject if not.
**** $EQ_{CFG}$ is undecidable.
***** Proof
-

**** $A_{TM}$ is undecidable.
***** Proof by Contradiction
- Let $A_{TM} = \{<M,w>\}$ s.t $M$ is a $TM$ and $M$ accepts $w$.
- Assume some TM $H$ decides $A_{TM}$ then,
  - $H$ on $<M,w>$ accepts iff $M$ accepts $w$ and rejects iff $M$ rejects $w$.
- Use $H$ to construct a TM $D$ s.t,
  - $D$ on input $<M>$,
    1. Simulate $H$ on input $<M,<M>>$.
    2. Accept if $H$ rejects and reject if $H$ accepts.
- This implies that,
  - $D$ accepts $<M>$ iff $M$ doesn't accept $<M>$.
  - $D$ accepts $<D>$ iff $<D>$ doesn't accept $D$ (if we replace $<M>$ to $<D>$).
- Contradiction. QED.
**** Proofs using reductions
We use our fact that $A_{TM}$ is undecidable to show other problems are undecidable.
***** If functions $f,g : \ \Sigma^* \ \rightarrow \Sigma^*$ are computable then so is $f \circ g$.
- The output of $f$ is fed to $g$ as input.
***** If $\rho: \ P \preccurlyeq_{c} Q$ and $\rho^{'}: \ Q \preccurlyeq_{c} R$ then $\rho \circ \rho^{'} : \ P \preccurlyeq_{c} R$.
****** Proof
- As composition is computable then so is $\rho \circ \rho^{'}$.
- It is also a reduction as,
  - $x \in P$
    - iff $\rho(x) \in Q$
    - iff $\rho^{'}(\rho(x)) \in R$
***** Reductions preserve decidability and SD
- When $\rho: \ P \preccurlyeq Q$ then,
  - If $Q$ is decidable then so is $P$.
  - If $Q$ is SD then so is $P$.
****** Mapping Reductions
******* If $A \le_{m} B$ and $B$ is decidable the so is $A$
******** Proof
- Assume TM $R$ decides $B$ then we can construct a TM $S$ s.t,
  - $S =$ on input $w$
    1. Compute $f(w)$.
    2. Run $R$ on $f(w)$ to test if $f(w) \in B$.
    3. If $R$ halts then result of $R$ is our result.
********* Corollary: If $A \le_{m} B$ and $A$ is undecidable then so is $B$.
****** If $A \le_{m} B$ and $B$ is T-recognizable (SD) the so is $A$.
******* Corollary: If $A \le_{m} B$ and $B$ is not T-recognizable (SD) then $A$ is not SD either.
***** $HALT_{TM}$ is undecidable.
****** Proof
- Let $HALT_{TM} = \{<M,w>\}$ s.t $M$ halts on input $w$.
- Let $R$ be the decider for $HALT_{TM}$ and $S$ be a decider s.t,
  - $S =$ on input $<M,w>$,
    1. Use $R$ to test if $M$ halts on $w$ and reject if it does not.
    2. Simulate $M$ on $w$ until it halts.
    3. If $M$ accepts then accepts and reject otherwise.
- As shown above if $R$ exists then we can decide $A_{TM}$ which is not possible. QED.
***** $E_{TM}$ is undecidable
- This problem is not even SD because its compliment is.
****** Proof
- Let $E_{TM} = <M>$ s.t $M$ is a TM and $L(M) = \phi$.
- Let $R$ be the decider for $E_{TM}$ then we can construct a TM $S$ s.t,
  - $S =$ on input $<M,w>$,
    1. Transform $M$ to new $M_w$ which works like $M$ except the it always rejects strings $x$ if $x \not{=} w$.
       - So, $L(M_w) = \begin{cases} \{w\} & \text{if M accepts w}\\ \phi & \text{if M rejects w} \end{cases}$
    2. Use $R$ to test if $L(M_w) = \phi$.
    3. If $M$ rejects $w$ then reject else if $M$ accepts $w$ then accept.
- As, $R$ can decide $A_{TM}$ which is undecidable we have a contradiction. QED.
***** $\bar{E_{TM}}$ is undecidable
**** Denotational/stable Properties
***** Rice's Theorem: Every denotational/stable property of Turing-acceptor is undecidable.
****** Proof
- Assume two acceptors $E$ and $A$ such that and here trivial means either yes or no and non-trivial means sometimes yes and sometimes no,
  - $L(E) = \phi$, $E$ recognizes $\phi$.
  - $E \notin P$ (it won't matter).
  - $P$ is not trivial and $A \in P$.
- So, deciding $P$ does two things,
  - It allows us to distinguish $E$ from $A$ as one accepts $\phi$ and other does not.
  - It allows us to distinguish whether a Turing machine $M$ accepts or does not accept $\epsilon$.
- We can construct a reduction, $\rho: \ \epsilon-\text{ACCEPT} \preccurlyeq_{c} P$,
  - Given $M$ build a new acceptor $M^{'}$ s.t $M^{'} = \rho(M)$
  - On input $x$, $M^{'}$ disregards $x$ and runs $M$ on $\epsilon$.
  - If $M$ accepts $\epsilon$ then $M^{'}$ runs $A$ on $x$. If $M$ does not then disregard everything, do nothing.
  - So we have,  $L(M^{'}) = \begin{cases} L(A) & \text{if M accepts } \epsilon \\ \phi = L(E) & \text{if M does not accept } \epsilon \end{cases}$.
  - So, $M$ accepts $\epsilon$ if $M^{'} = \rho(M) \in P$ i.e if $M^{'}$ has property $P$.
  - As we know that $\epsilon-\text{ACCEPT}$ is undecidable we can say that every non trivial denotational/stable property is undecidable or no denotational/stable property is decidable unless trivial.
*** Summary
| Semi-decidable          | Decidable            |
|-------------------------+----------------------|
| $L$ recognized by TA    | $L$ recognized by TD |
| CE                      | OE                   |
| $L$ has a certification | $L$ $\bar{L}$ are SD |
**** How to prove a problem $P$ is decidable?
- $P$ is recognized by a decider.
- $P$ is finite or orderly enumerated.
- Both $P$ and $\bar{P}$ are SD.
- $P$ is definable using union, intersection and compliment (or difference) from decidable problems.
**** How to prove a problem $Q$ is SD?
- $Q$ is recognized by an acceptor/recognizer.
- $Q$ is computably enumerated.
- $Q$ has a decidable certification.
- $Q$ is defined using union, intersection from SD languages.

*** Closure Properties
**** Decidable Problems
- Let $P$ and $Q$ be decision problems (decidable languages) referring to the same instances (maybe strings or graphs) and suppose we have algorithms $A_P$ and $A_Q$ that decide $P$ and $Q$ respectively.
***** The complement of $P$ i.e $\bar{P}$ is decidable.
****** Proof
- To decide if some input $w \in \bar{P}$,
  - Run $A_P$ on input $w$ and do the opposite of what $A_P$ outputs, i.e reject if accept and accept if reject.
***** The intersection of $P$ and $Q$ is decidable.
****** Proof
- So, intersection is basically like an $AND$. To decide if some input $w \in P \cap Q$,
  - First, run $A_P$ on $w$ if it rejects then reject immediately else if it accepts run $A_Q$ on $w$ if it rejects then reject and if it accepts then accept.
***** The union of $P$ and $Q$ is decidable.
****** Proof
- So, union is basically like an $OR$. So, to decide if some input $w \in P \cup Q$,
  - Run $A_P$ on $w$ and accept if accepts else if it rejects run $A_Q$ on $w$ and accept if it accepts and reject if it rejects.
***** The concatenation of $P$ and $Q$ is decidable
****** Proof
- Let $P$ and $Q$ be languages. A string $w$ is in the concatenation of $P$ and $Q$ if you can write it as $w=ab$, where
  $a \in P$ and $b\in Q$. This means that you can split $w$ into two halves. The first half is a string from $P$ and the second half is a
  string from $Q$. If you have two decidable languages $P$ and $Q$, you can make a decider for $P$ concatenated with $Q$ as follows:
  + Given a two-tape nondeterministic Turing machine,
    1. Non-deterministically guess where to split the string into two parts $w=ab$
    2. Run the first machine to make sure the first half is in $P$
    3. If it isn't, reject.
    4. Run the second machine to make sure the second half is in $Q$
    5. If it isn't, reject.
  + If the string really is in the concatenation of $P$ and $Q$, then one of these guesses will be correct; that nondeterministic branch will accept, so the computation itself accepts.
***** The kleene star of decidable language $P$ i.e $P^*$ is decidable
**** Semi-decidable Problems
- We cannon run Turing machines sequentially as we did for decidable languages here because the first can go into loop never reaching the next steps in the sequence.
- Suppose $L_0, L_1 \subseteq \Sigma^*$ are semi-decidable i.e they have certifications $\vdash_{0}$, $\vdash_{1}$ respectively.
***** The union of two SD languages is SD.
****** Proof using certifications
- Let $c \vdash x$ then we can say that $\vdash$ is decidable as it is union of two decidable sets i.e $c \vdash_{0} x \ \text{OR} \ c \vdash_{1} x$ ,
- $\vdash$ is a certification because,
  - $x \in L_0 \cup L_1$
    - iff $x \in L_0$ OR $x \in L_1$
    - iff for some $c$, $c \vdash_{0} x$ or $c \vdash_{i} x$.
    - iff $c \vdash x$ for some $c$. (from defn of $\vdash$)
****** Proof using TM
- Let $M_0$ and $M_1$ be T-recognizers for $L_0$ and $L_1$ respectively.
- We can run $M_0$ and $M_1$ simultaneously i.e one step of $M_0$ followed by one step of $M_1$ and accept when any one of them accepts and reject otherwise.
***** The intersection of two SD languages is SD
****** Proof using certifications
- Define $c \vdash x$ to hold iff $c$ is $<c_0,c_1>$ where $c_0 \vdash_{0} x$ AND $c_1 \vdash_{1} x$.
- $\vdash$ is decidable because $\vdash_{0}$ and $\vdash_{1}$ are decidable.
- It is a certification because,
  - $x \in L_0 \cap L_1$
    - iff $x \in L_0$ AND $x \in L_1$
    - iff for some $c_0, c_1$, $c_0 \vdash_{0} x$ or $c_1 \vdash_{1} x$.
    - iff $c \vdash x$ for some $c$. (from defn of $\vdash$)
***** The complement of a SD language need not be SD
- As if it were then every semi-decidable language would be decidable as per this [[*If $A$ and $\bar{A}$ are T-recognizable (SD) the $A$ is decidable.][theorem]] .
**** Undecidable Problems
***** Collection of undecidable problems/languages is *not* closed under union, intersection, concatenation, compliment, kleene star so not closed under anything.
*** Problems
**** If $D$ is decidable and $U$ is undecidable
 - $D \cap U$: This language is the intersection of $D$ and $U$, which contains all strings that belong to both $D$ and $U$. Since $U$ is undecidable, this language is also undecidable.
 - $D \cup U$: This language is the union of $D$ and $U$, which contains all strings that belong to either $D$ or $U$. Since $D$ is decidable, this language is also decidable.
 - $D - U$: This language is the set difference of $D$ and $U$, which contains all strings that belong to $D$ but not $U$. Since $D$ is decidable, this language is also decidable.
 - $U - D$: This language is the set difference of $U$ and $D$, which contains all strings that belong to $U$ but not $D$. Since $U$ is undecidable, this language is also undecidable.
 - $D \cdot U$: This language is the concatenation of $D$ and $U$, which contains all strings that can be formed by concatenating a string from $D$ with a string from $U$. Since $U$ is undecidable, this language is also undecidable.
***** $D$ is a decidable language, and $U$ is undecidable and disjoint from $D$ then $D \cup U$
- If $D$ is a decidable language and $U$ is an undecidable language that is disjoint from $D$
  (i.e., no string belongs to both $D$ and $U$), then we can conclude that the language $D \cup U$ is decidable.
  This is because the language $D \cup U$ contains all strings that belong to either $D$ or $U$, and since $D$ is
  decidable, we can use a decider for $D$ to determine whether a given string belongs to $D \cup U$. Therefore, the language $D \cup U$ is decidable.
